"""Read-only environment checks and isolated tests; never sync or send Gmail.

Run with the project's Python. Reports deliberately exclude token values,
mail content, task titles, account addresses, and raw exception messages.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from mailtaskagent.config import PROJECT_ROOT, load_settings
from mailtaskagent.gmail_source import (
    build_gmail_service, load_gmail_source_settings, load_gmail_send_source_settings,
)


def command(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=PROJECT_ROOT, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", check=False)


def oauth_check(settings, *, send=False):
    try:
        build_gmail_service(settings, allow_interactive_auth=False, include_send_scope=send)
        return {"ready": True, "check": "credential_refresh_only_not_send_or_mail_fetch"}
    except Exception as exc:
        payload = next((item for item in exc.args if isinstance(item, dict)), {})
        code = payload.get("error")
        # Only well-known codes; do not serialize arbitrary provider responses.
        return {"ready": False, "error_type": type(exc).__name__,
                "oauth_code": code if code in {"invalid_grant", "invalid_client", "access_denied"} else None}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check-gmail", action="store_true")
    args = parser.parse_args()
    output = args.output.resolve()
    if output.exists():
        raise SystemExit("Evidence already exists; use a new output filename.")
    settings = load_settings()
    tracked = command("git", "ls-files", "-z").stdout.split("\0")
    code_files = [p for p in tracked if p and (p.startswith(("src/", "tests/", "scripts/"))
                  or p in {"app.py", "pyproject.toml", "requirements.txt", "requirements-gmail.txt"})]
    hashes = {p: hashlib.sha256((PROJECT_ROOT / p).read_bytes()).hexdigest()
              for p in code_files if (PROJECT_ROOT / p).is_file()}
    db_checks = {}
    for label, path in {"operation": settings.database_path,
                        "demo": settings.database_path.with_name(settings.database_path.stem + "-demo.db")}.items():
        if not path.exists():
            db_checks[label] = {"exists": False}
            continue
        try:
            with sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True) as db:
                db_checks[label] = {
                    "exists": True,
                    "integrity": [r[0] for r in db.execute("PRAGMA integrity_check")],
                    "journal_mode": db.execute("PRAGMA journal_mode").fetchone()[0],
                    "task_count": db.execute("SELECT count(*) FROM tasks").fetchone()[0],
                    "history_count": db.execute("SELECT count(*) FROM histories").fetchone()[0],
                }
        except sqlite3.Error as exc:
            db_checks[label] = {"error_type": type(exc).__name__}
    result = command(sys.executable, "-X", "utf8", "-m", "pytest", "-q", "-p", "no:cacheprovider")
    summaries = [line for line in result.stdout.splitlines() if "passed" in line or "failed" in line]
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "baseline_commit": command("git", "rev-parse", "HEAD").stdout.strip(),
        "branch": command("git", "branch", "--show-current").stdout.strip(),
        "tracked_changes": command("git", "diff", "--name-only").stdout.splitlines(),
        "code_sha256": hashes,
        "python": sys.version.split()[0],
        "pytest": {"exit_code": result.returncode, "summary": summaries[-1:]},
        "llm_mode": settings.llm_mode,
        "llm_model": settings.model,
        "rag_enabled": settings.task_context_rag_enabled,
        "rag_max_retries": settings.task_context_rag_max_retries,
        "approved_send_enabled": settings.gmail_approved_send_enabled,
        "databases": db_checks,
        "gmail": {},
        "limits": ["No new Gmail messages fetched or sent by this audit script",
                   "pytest uses isolated synthetic inputs, not a fresh Gmail E2E run",
                   "Existing evidence is not regenerated by this script"],
    }
    if args.check_gmail:
        report["gmail"] = {"read": oauth_check(load_gmail_source_settings()),
                           "send": oauth_check(load_gmail_send_source_settings(), send=True)}
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({k: v for k, v in report.items() if k != "code_sha256"}, ensure_ascii=False))
    raise SystemExit(result.returncode)


if __name__ == "__main__":
    main()
